### PR TITLE
Improve code for Error handling

### PR DESCRIPTION
**Pull request by shekhar-j**
# Description
To provide meaningful errors and reduce resources consumption. 

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [X] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [X] I have verified that new and existing unit tests pass locally with my changes
- [X] I have not allowed coverage numbers to degenerate
- [X] I have maintained at least 80% code coverage
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [X] Acceptance tests

### CODE REVIEW

**Review by doriac11 — APPROVED** [review]

**Review by nikitajoshi1 — APPROVED** [review]

**Comment by shekhar-j** [comment]
run e2e tests

**Comment by shekhar-j** [comment]
run e2e test

**Comment by shekhar-j** [comment]
run e2e test

**Comment by shekhar-j** [comment]
run e2e test

**Comment by shekhar-j** [comment]
run e2e test

**Comment by shekhar-j** [comment]
run e2e tests

**Comment by shekhar-j** [comment]
run e2e test

**Pull request merged**
